name: pipeline

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        npm run build
        npm ci
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: npm run test
